extraction:
  frequency_days: 2
  groups:
    - username: "@leetcode_answers"
      name: "LeetCode Answers"

      username: "@cognizant_exam_discussion_group"
      name: "Cognizant Exam Discussion Group"
 

dm_limits:
  max_per_day: 1

promotion_channel: "Jobs_Lelo"
