levels:
  level_0:
    message: "bro are you looking for placements i have some hr contacts hiring currently ??"
    
  level_2:
    messages:
      - "i have some emails you can use for cold mail they are hiring currently. if you want i can send"
    
  level_4:
    messages:
      - "sending just 1 min"
      - "[EMAIL_XLSX]"
      - "while cold mailing just remember to have one deployed project"
      - "also u can join this group https://t.me/Jobs_Lelo there we post daily job updates verified hr contacts and sometimes even referrals a lot of ppl find it useful"
      
  level_5:
    message: "While applying the job updates try to contact me if possible I will provide the referral through my contact"

categorization_prompt: |
  Analyze this user message and determine if they are looking for job placements/internships.
  Respond with only "yes" or "no".
  Context: This message is from a Telegram jobs group.
  Message: {message}

response_prompts:
  level_1: |
    Determine whether the user's reply indicates they are looking for placements or internships.
    Reply with only one of: yes, no, or unclear.
    User reply: {message}

  level_3: |
    Determine whether the user's reply is a request for the contact/emails (i.e. asking you to send the hiring contacts).
    Reply with only one of: yes, no, or unclear.
    User reply: {message}
