# Telegram API Credentials
telegram:
  api_id: 39367448
  api_hash: "4b9a7be7ded2eb99822fa7eef2f935c9"
  session_name: "session"

# Source Groups/Channels to fetch posts from
sources:
  - username: "@jobs_and_internships_updates"
    name: "jobs_and_internships_updates"
  - username: "@jobs_and_internships_updates1"
    name: "jobs_and_internships_updates1"
  - username: "@internfreak"
    name: "internfreak"
  - username: "@TechUprise_Updates"
    name: "TechUprise_Updates"
  - username: "@dot_aware"
    name: "dot_aware"
  - username: "@gocareers"
    name: "gocareers"
  - username: "@join_Daily_Jobs_Placement_Update"
    name: "join_Daily_Jobs_Placement_Update"
  - username: "@TorchBearerr"
    name: "TorchBearerr"
  - username: "@off_campus_jobs_and_internships"
    name: "off_campus_jobs_and_internships"
  - username: "@TechJobUpdatesDaily"
    name: "TechJobUpdatesDaily"
  - username: "@internshiptojobs"
    name: "internshiptojobs"
  - username: "@getjobss"
    name: "getjobss"

# Destination Groups/Channels to post messages to
destinations:
  - username: "@Jobs_Lelo"
    name: "Primary Destination"
  # - username: "@another_dest"
  #   name: "Secondary Destination"

promotion_destinations:
  channels:
       - "@my_promotions"


  messages:
    fresher_jobs:
      text: "üî• Freshers jobs available now"

    remote_jobs:
      text: "üåç Remote job openings ‚Äì apply today"

    internship_alert:
      text: "üéì Internship opportunities open"

    



# Fetching Configuration
fetching:
  minutes_to_fetch: 30    # Fetch posts from last N minutes (360 = 6 hours)
  messages_per_fetch: 10  # Max messages to fetch per source
  batch_sleep_seconds: 0.5

# Posting Configuration
posting:
  delay_between_posts_seconds: 0.5

# Rate Limiting
rate_limiting:
  max_retries: 3
  retry_delay_seconds: 2

# Logging
logging:
  level: "INFO"                      # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "telegram_bot.log"
  console_output: true

# Storage
storage:
  posts_database: "fetched_posts.db"
  enable_caching: true
