# Telegram API Credentials
telegram:
  api_id: 39367448
  api_hash: "4b9a7be7ded2eb99822fa7eef2f935c9"
  session_name: "session"

messages:
  fresher_jobs:
    - text: "Hello All we have a community where we share Job refferal .If you are looking for opportunities or can provide referrals please join https://t.me/Jobs_Lelo"
      path: "D:\\Desktop_C\\OPEN SOURCE\\telegram\\contacts.png"
      time_filter: "09:00-18:00"
      username: "@tcs_codevita_ans"

    - text: "If anyone is looking for job opportunities in startups can check the job postings here at @Jobs_Lelo! ğŸ”¥"
      path: "assets/promo_reffereal.png"
      time_filter: "09:00-18:00"
      username: "@tcs_codevita_ans"      

  remote_jobs:
    text: "ğŸŒ Remote job openings apply today"

  internship_alert:
    text: "ğŸ“ Internship opportunities open"

